### ISSUE TITLE
Don't calculate IPC scaling using stats["IPC"].mean()

### ISSUE THREAD

**Issue by Jonathan3145** [numericalalgorithmsgroup/pypop#17]
Instead use something like

(stats["Useful Instructions"].sum() / stats["Useful Cycles"].sum())/
(self._stats_dict[ref_key].stats["Useful Instructions"].sum()/self._stats_dict[ref_key].stats["Useful Cycles"].sum())

**Comment by ptooley** [comment]
Doing it this way ensures that the IPC is weighted by instructions per thread rather than being indifferent to relative workload
