### ISSUE TITLE
Spurious message about missing .row and .pcf files

### ISSUE THREAD

**Issue by Jonathan3145** [numericalalgorithmsgroup/pypop#23]
Running trace analysis on trace_np48_nt1_test.filter3.prv complains about not being able to find trace_np48_nt1_test.pcf and trace_np48_nt1_test.row, i.e. 

/fserver/jonathanb/pop/pypop_stuff/pypop/pypop/dimemas.py:145: UserWarning: Could not find /fserver/jonathanb/POP_trace_data/CASTEP/Solid_Benzene/junk/trace_np48_nt1_test.row, dimemas may fail or produce invalid data
  warnings.warn(
/fserver/jonathanb/pop/pypop_stuff/pypop/pypop/dimemas.py:145: UserWarning: Could not find /fserver/jonathanb/POP_trace_data/CASTEP/Solid_Benzene/junk/trace_np48_nt1_test.pcf, dimemas may fail or produce invalid data
  warnings.warn(

**Comment by ptooley** [comment]
J suggests likely due to double use of splitext...   Needs a robustness check and probably a util routine.  (Should grep for "prv" and "row" to see where it is used...)
