### ISSUE TITLE
Multi-locus Analysis 

### ISSUE THREAD

**Issue by Nash0990** [numericalalgorithmsgroup/pypop#42]
Ran an analysis on ~25000 samples with 5 locus each, analysis runs smooth but when in the results looks like the Multi-locus analysis was not performed with the comment saying "Too many rows for haplotype program" and also blank Pairwise LD estimates. 

Is there a way to process this huge number of samples?

**Comment by ptooley** [comment]
Hi @Nash0990  I believe you have the wrong project. I think the PyPOP genomics repository is here: https://github.com/alexlancaster/pypop
